# Generated by Django 3.2.8 on 2021-10-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price_orig', models.CharField(max_length=100, verbose_name='Preço Original')),
                ('price_dell', models.CharField(max_length=100, verbose_name='Preço com Desconto')),
                ('discount', models.CharField(max_length=100, verbose_name='Desconto')),
                ('freight', models.CharField(max_length=100, verbose_name='frete')),
                ('name_proc', models.CharField(max_length=100, verbose_name='Processador')),
                ('name_so', models.CharField(max_length=100, verbose_name='Sistema Operacional')),
                ('name_placa_de_video', models.CharField(max_length=100, verbose_name='Sistema Operacional')),
                ('name_monitor', models.CharField(max_length=100, verbose_name='Monitor')),
                ('name_ssd', models.CharField(max_length=100, verbose_name='SSD')),
                ('name_ram', models.CharField(max_length=100, verbose_name='Memória RAM')),
                ('description', models.CharField(max_length=100, verbose_name='Descrição')),
            ],
        ),
    ]
