# Generated by Django 3.2.8 on 2021-10-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='name_placa_de_video',
        ),
        migrations.AddField(
            model_name='notebook',
            name='name_video_card',
            field=models.CharField(max_length=100, null=True, verbose_name='Placa de vídeo'),
        ),
    ]
